version: '3'
services:
  app:
    networks:
      - internal
    ports:
      - "8000:80"
    build: ./docker/app
    container_name: tc-practice-app
    volumes:
      - ./:/var/www/html
    healthcheck:
      test: ["CMD", "curl -f http://localhost/"]
      interval: "1s"
      timeout: "1s"
      retries: 0
    environment:
      TZ: 'Asia/Tokyo'
    depends_on:
      - db

  db:
    networks:
      - internal
    image: mysql:8.4.3
    container_name: tc-practice-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tc_practice
      MYSQL_USER: tc_user
      MYSQL_PASSWORD: tc_user
      MYSQL_TCP_PORT: 3307
      TZ: 'Asia/Tokyo'
    platform: linux/x86_64
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
    expose:
      - 3307

  phpunit:
    networks:
      - internal
    build: ./docker/phpunit
    container_name: tc-practice-phpunit
    environment:
      TZ: 'Asia/Tokyo'
    depends_on:
      - db
    volumes:
      - ./:/src
    tty: true

networks:
  internal:
    driver: bridge
